[dependencies]
anyhow = "1.0"
itertools = "0.12"
num = { version = "0.4.1", features = ["num-bigint"] }
parse-display = "0.8"
regex = "1"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day08"
version = "0.1.0"
