[package]
authors = ["Janus <janus@insignificancegalore.net>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
regex = "1"
itertools = "0.12"
parse-display = "0.8"
# apply = "0.3.0"
# num = "0.4"