[dependencies]
anyhow = "1.0"
itertools = "0.12"
nom = {version="7.1.3", features=["alloc"]}
nom-regex = "0.2.0"
parse-display = "0.8"
regex = "1"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day04"
version = "0.1.0"
