[package]
version = "0.1.0"
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
parse-display = "0.4"
regex = "1"
itertools = "0.9"
apply = "0.3.0"
num = "0.3"
