[package]
authors = ["Janus <janus@insignificancegalore.net>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
parse-display = "0.5.3"
regex = "1"
itertools = "0.10"
apply = "0.3.0"
num = "0.4"