[dependencies]
anyhow = "1.0"
itertools = "0.10"
ndarray = "0.15.6"
parse-display = "0.6"
regex = "1"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day08"
version = "0.1.0"
