[package]
name = "day23"
version = "0.1.0"
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day11 = {path="../day11"}
