[dependencies]
anyhow = "1.0"
intervaltree = "0.2.7"
itertools = "0.12"
parse-display = "0.8"
regex = "1"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day05"
version = "0.1.0"
