[dependencies]
anyhow = "1.0"
itertools = "0.12"
nom = { version = "7.1.3", features = ["alloc"] }
parse-display = "0.8"
regex = "1"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day19"
version = "0.1.0"
