[dependencies]
anyhow = "1.0"
itertools = "0.10"
parse-display = "0.5.3"
regex = "1"
bitvec = "0.22.3"
nom-bitvec = "0.2.0"
hex = "0.4.3"
nom = "7.1"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day16"
version = "0.1.0"
