[dependencies]
anyhow = "1.0"
itertools = "0.12"
parse-display = "0.8"
regex = "1"
vecmath = "1.0.0"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day23"
version = "0.1.0"
