[dependencies]
anyhow = "1.0"
itertools = "0.10"
nom = "7.1.1"
parse-display = "0.6"
regex = "1"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day16"
version = "0.1.0"
