[dependencies]
anyhow = "1.0"
apply = "0.3.0"
itertools = "0.9"
num = "0.3"
parse-display = "0.5"
regex = "1"

[package]
authors = ["Janus <janus@insignificancegalore.net>"]
edition = "2021"
name = "day02"
version = "0.1.0"
